### DISCUSSION TITLE
Modules: Hello world example module

### DISCUSSION THREAD

**Discussion by simanadler** [fybrik/fybrik#255] [Ideas]
Developers working on creating a new module suggested that we provide a "hello world" module that they can use as a starting point.

They would also like documentation describing how to create a module (initial version exists) and test it (lacking).
I'm not suggesting automated testing but rather instructions to the developer about how to test it.

**Comment by roee88** [comment]
How do you imagine an hello world module to look like?

**Reply by shlomitk1** [reply]
Modules can be controllers that process a specific CRD but can also be a deployment of some container that processes data. In the second case, how do we check for readiness? Read is a special case when it is ready once the pod is running, but it is not always the case. 

Taking data quality as an example, there is some software that reads and processes the data. 
Two questions: what is the interface with the users and how it tells its status. Release notes can include a link to the output (can we expose some mount file of the pod?) Do we want to include some "description" field in the readiness indicator, as was done for error/success/failure? Which means that the module developers would need a CRD for each module.

**Reply by roee88** [reply]
In my view there are things that act like jobs and there are things that act like services and that's it. Nothing is special and generally nothing other than the reconcile status and errors is needed as part of the status. Please open a separate discussion for data quality. I believe that you mix the personas (which persona cares about data quality, what we do in bad quality).

**Reply by simanadler** [reply]
@roee88 This issue was opened to start a discussion about how anyone wanting to develop a module gets started.  One of such developers suggested that we have a "hello world" module.  The question is not specific to a data quality module.

As for status, I think there are modules that provide in line processing (in memory) as data is read or written (along the lines of what Ziv and I did last year) and there are modules that run as jobs.  Perhaps the former is what you mean by services?  

In any case, perhaps jobs do indeed need to provide a status whereas the latter do not.  In any case, I think we need to differentiate between the two in the module definitions.

That said, I think we can start by providing a "hello world" for a job type service first.

**Reply by roee88** [reply]
@simanadler we previously differentiated between the two, but never used this field so we removed it. If this will be needed in the future then we'll add it.

As for a hello world module, repeating my original question - did you imagine something concrete already? Should we make something up in this thread?

**Comment by simanadler** [comment]
@roee88 @shlomitk1 @ronenkat @cdoron I think we should start by creating two hello world templates:
* copy - reads from a source, writes to a target and can perform optional transformations.  Assume the service that does the actual copy is an external service, and that the module is a client of that external service.  Provides status back to manager.  Only code the user should have to write is the invocation of the external service, and updating the status.

* in memory eval/transform - reads data via a read module (ex: existing arrow flight module), does whatever it wants to the data (transforms, data quality eval, ...), and does one or more of the following:
a) writes data to output memory
b) writes info for user to mechanism used for sharing info with user (??) - _See discussion https://github.com/IBM/the-mesh-for-data/discussions/266_
_Note: This is a type of module that we don't currently have, but we need to enable enforcement extensions._
The aim should be to limit the amount of kubernetes knowledge required by the module developers.  We also need clear and simple instructions about how to test the modules.

**Comment by eletonia** [comment]
@simanadler @ronenkat @roee88 @cdoron 
As discussed in the meeting today, we think it would be good to start with the hello world copy module template which will not actually copy data but will act as a placeholder for the client's module code or a call to an external service. We should start with the template for the M4D Module CRD, Helm chart, and a docker image which has the dummy copy code returning something like `copy successful`. To trigger this copy module, we will need to provide a flag in the catalog for a format of the data which is different from the format that the data scientist requested in the `m4d-application`

**Reply by ronenkat** [reply]
from a use-case perspective we should create an asset with a specific format (e.g., Kafka) and on M4DApplication specify a need for a different format (e.g., S3).

**Reply by shlomitk1** [reply]
For testing a dummy copy module, M4DApplication should request copy explicitly but not read (i.e. no workload selection).
```
apiVersion: app.m4d.ibm.com/v1alpha1
kind: M4DApplication
metadata:
  name: <name>
spec:
  selector:
   workloadSelector:
     matchLabels: {}
  appInfo:
    purpose: copy
    role: Data Owner
  data:
    - dataSetID: <asset identifier>
      requirements:
        copy:
          required: true
        interface:
          protocol: <protocol supported by the module>
          dataformat: <format supported by the module>

```

**Reply by cong78** [reply]
hi @eletonia it sounds like a great idea and exactly needed for my work on creating a Data Engine module for Data Stage. 
Can I ask do you have some initial work done already?

**Reply by eletonia** [reply]
Hi @cong78 We made this [hello-world-module repo](https://github.com/mesh-for-data/hello-world-module) which has all the files for an example module. `m4dapplication.yaml` is still a work in progress but you should be able to do all the other steps to make a Helm chart for your Data Engine module and deploy it.

**Reply by cong78** [reply]
@eletonia Awesome! I will try it now. Thanks!

**Reply by eletonia** [reply]
Hi @cong78 The [hello-world-module repo](https://github.com/mesh-for-data/hello-world-module) is updated with the code and steps used in our latest internal demo. Let me know if you have any questions!

**Reply by cong78** [reply]
hi, @eletonia Thanks a lot I have pulled the changes to my repo https://github.com/cong78/etl-engine-module . But I have some local errors in verifying the syntax of the chart. Is that possible to set up a call with you? I also have some other questions and maybe you have ideas as well.

**Reply by cong78** [reply]
@eletonia  btw I am running into a parsing error with helm verify and not sure if I need to change anything to have it verified: 
[ERROR] templates/: template: etl-engine-module/templates/configmap.yaml:10:3: executing "etl-engine-module/templates/configmap.yaml" at <tpl (.Files.Get "files/conf.yaml") .>: error calling tpl: error during tpl function execution for "{{- $copy := .Values.copy | default dict -}}\n{{ if $copy }}\n{{- $source := $copy.source | default dict -}}\ndata:\n  - format: {{ $copy.source.format | quote }}\n    vault_credentials:\n      address: {{ $copy.source.vault.address | quote}}\n      authPath: {{ $copy.source.vault.authPath | quote}}\n      role: {{ $copy.source.vault.role }}\n      secretPath: {{ $copy.source.vault.secretPath | quote}}\n    {{- $connection := $copy.source.connection | default dict -}}\n    {{ if $connection.s3 | quote}}\n    s3.bucket: {{ $connection.s3.bucket | quote}}\n    s3.endpoint: {{ $connection.s3.endpoint | quote}}\n    {{ end }}\n    connection.name: {{ $connection.name | quote }}\n{{ else }}\ndata: []\n{{ end }}": template: etl-engine-module/templates/configmap.yaml:3:20: executing "etl-engine-module/templates/configmap.yaml" at <$copy.source>: can't evaluate field source in type []interface {}

**Reply by eletonia** [reply]
Hi @cong78 Sure we can set up a call once I am able to message you on Slack. It will be easier to discuss on there. 
I have seen that parsing error before. It might be because you have values in your `values.yaml` file. This [conf.yaml](https://github.com/mesh-for-data/hello-world-module/blob/main/hello-world-module/files/conf.yaml) file assumes that the copy/read values are passed into the module from the M4D-manager so they are empty in my [values.yaml ](https://github.com/mesh-for-data/hello-world-module/blob/main/hello-world-module/values.yaml)file. If you want to test with values filled in, use another version of `conf.yaml` [here](https://github.com/mesh-for-data/hello-world-module/blob/4a010e6d6d81366cb9af18d5843806face225d76/hello-world-module/files/conf.yaml)

**Reply by cong78** [reply]
> Hi @cong78 Sure we can set up a call once I am able to message you on Slack. It will be easier to discuss on there.
> I have seen that parsing error before. It might be because you have values in your `values.yaml` file. This [conf.yaml](https://github.com/mesh-for-data/hello-world-module/blob/main/hello-world-module/files/conf.yaml) file assumes that the copy/read values are passed into the module from the M4D-manager so they are empty in my [values.yaml ](https://github.com/mesh-for-data/hello-world-module/blob/main/hello-world-module/values.yaml)file. If you want to test with values filled in, use another version of `conf.yaml` [here](https://github.com/mesh-for-data/hello-world-module/blob/4a010e6d6d81366cb9af18d5843806face225d76/hello-world-module/files/conf.yaml)

Ah got it. Thanks! 
I have another question is it has to be the exact format of the Copy or Read from the values.yaml template? Because for the ETL engine module that I am working on, it also needs to configure some other parameters that are Data Stage specific, such as Project name, Job name, etc. Can I modify that values.yaml template to receive those things as well?

**Reply by eletonia** [reply]
@shlomitk1  If Cong adds new parameters needed for Data Stage, how will the M4D-manager handle those?

**Reply by shlomitk1** [reply]
It's perfectly fine to have more parameters in the module - copy arguments defined by manager, while having default values for other params. For example, implicit copy module has some params used inside BatchTransfer with default values configured in values.yaml.

**Reply by roee88** [reply]
These values that are not passed by manager can also be set in M4DModule (overriding the defaults) in `spec.chart.values`.

**Comment by cong78** [comment]
hi @eletonia I am working on the hello-world-module/files/conf.yaml file to have both source and destination properties read from the value.yaml file. 


Here is the one that I am trying to make:.

```
{{- $copy := .Values.copy | default dict -}}
{{ if $copy }}
{{- $source := $copy.source | default dict -}}
source:
  - format: {{ $copy.source.format | quote }}
    vault_credentials:
      address: {{ $copy.source.vault.address | quote}}
      authPath: {{ $copy.source.vault.authPath | quote}}
      role: {{ $copy.source.vault.role }}
      secretPath: {{ $copy.source.vault.secretPath | quote}}
    {{- $connection := $copy.source.connection | default dict -}}
    connection.name: {{ $connection.name | quote }}
    {{ if $connection.s3 | quote}}
    s3.bucket: {{ $connection.s3.bucket | quote}}
    s3.endpoint: {{ $connection.s3.endpoint | quote}}
    {{ end }}
destination:
  - format: {{ $copy.destination.format | quote }}
    vault_credentials:
      address: {{ $copy.destination.vault.address | quote}}
      authPath: {{ $copy.destination.vault.authPath | quote}}
      role: {{ $copy.destination.vault.role }}
      secretPath: {{ $copy.destination.vault.secretPath | quote}}
    {{- $connection := $copy.destination.connection | default dict -}}
    connection.name: {{ $connection.name | quote }}
    {{ if $connection.s3 | quote}}
    s3.bucket: {{ $connection.s3.bucket | quote}}
    s3.endpoint: {{ $connection.s3.endpoint | quote}}
    {{ end }}
{{ else }}
data: []
{{ end }}
```
With helm verify it ends up:
```
# Source: etl-engine-module/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: rel1-etl-engine-module-config
data:
  conf.yaml: |-
    source:
      - format: 
        vault_credentials:
          address: 
          authPath: 
          role: 
          secretPath: connection.name: 
        
        s3.bucket: 
        s3.endpoint: 
        
    destination:
      - format: 
        vault_credentials:
          address: 
          authPath: 
          role: 
          secretPath: connection.name: 
        
        s3.bucket: 
        s3.endpoint:
---
# Source: etl-engine-module/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: rel1-etl-engine-module
spec:
  template:
    spec:
      serviceAccountName: rel1-etl-engine-module
      securityContext:
        null
      containers:
      - image: "ghcr.io/cong78/etl-engine-module:latest"
        imagePullPolicy: 
        name: rel1-etl-engine-module
        env:
        volumeMounts:
        - name: rel1-etl-engine-module-volume
          mountPath: "/etl-engine-module"
          readOnly: true
      volumes:
      - name: rel1-etl-engine-module-volume
        configMap:
          name: rel1-etl-engine-module-config
          items:
          - key: conf.yaml
            path: conf.yaml
      restartPolicy: Never
  backoffLimit: 4
```

Any quick thoughts on what might be wrong? Or is it the right format?
