### DISCUSSION TITLE
Separating OPA installation from policy loading

### DISCUSSION THREAD

**Discussion by rohithdv** [fybrik/fybrik#420] [Developers]
We want to separate OPA installation from the way we load policies to OPA in mesh for data. This discussion deals with approaches to do the same.
We have implemented the below approach :
Assume we are working in the namespace <OPA_NAMESPACE>
Step 1. Delete all existing resources:

```
kubectl delete -f policy-editor.yaml
kubectl delete -f policy-editor-rolebinding.yaml
kubectl delete -f opa.yaml
kubectl delete configmap opa-json
kubectl delete configmap opa-policy
```

Step 2, Create Role and Rolebinding resources and associate them with the <OPA_NAMESPACE>.
`kubectl create -f policy-editor.yaml`

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
namespace:  <OPA_NAMESPACE>.
name: policy-editor
rules:
apiGroups: [""]
resources: ["configmaps"]
verbs: ["get", "list", "watch", "update", "patch"]
```

`kubectl create -f policy-editor-rolebinding.yaml`

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
name: policy-editor
namespace:  <OPA_NAMESPACE>.
roleRef:
kind: Role
name: policy-editor
apiGroup: rbac.authorization.k8s.io
subjects:
kind: Group
name: system:serviceaccounts:<OPA_NAMESPACE>.
apiGroup: rbac.authorization.k8s.io
```

Step 3. Deploy plain vanilla OPA with kube-mgmt using the command  kubectl create -f opa.yaml. The spec of the opa.yaml is given below.
```
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:latest
        args:
        - "run"
        - "--server"
        - "--log-level=debug"
        - "--set=decision_logs.console=true"
        ports:
        - name: http
          containerPort: 8181
      - name: kube-mgmt
        image: openpolicyagent/kube-mgmt:0.11
        args:
        - --require-policy-label
        - --policies=irltest1
        - --enable-data
```

Step 4. Create a Kustomization resource with only the data related files (json data)
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: opa-json
  files:
  - taxonomies.json
  - medical_taxonomies.json

```

Step 5. Load the data to OPA using kube-mgmt labelling approach (https://github.com/open-policy-agent/kube-mgmt)
```
kubectl kustomize ./ |kubectl label -f- --dry-run=client -o yaml --local openpolicyagent.org/data=opa > newjson.yaml
kubectl create -f newjson.yaml
```

Step 6. Create a Kustomization resource with only the policy related files (rego data)
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: opa-policy
  files:
  - data_policies/action_struct.rego
  - data_policies/auditing_struct.rego
  - data_policies/helper_functions.rego
  - data_policies/input_reader.rego
  - data_policies/taxonomies_unification.rego
  - data_policies/verify_correct_input.rego
  - sample_policies.rego
  - user_policies.rego
```

Step 7. Load the policies to OPA  using kube-mgmt labelling approach (https://github.com/open-policy-agent/kube-mgmt)
```
kubectl kustomize ./ |kubectl label -f- --dry-run=client -o yaml --local openpolicyagent.org/policy=rego > newpolicy.yaml
kubectl create -f newpolicy.yaml
```

One thing to discuss here is how to access helper data (json data) in policy files. One way to do this is given in [taxonomies_unification.rego](https://github.com/rohithdv/the-mesh-for-data/blob/59259df6bcdb3cdd4d5f5030fe7ce7effcf88845/third_party/opa/data-and-policies/data_policies/taxonomies_unification.rego#L8).

As seen in the above taxonomies_unification.rego file, there is a hardcoding of namespace to access data in the policy file. We can discuss if there are better ways to do the above.

To summarise,
Step 1 -2  deals with initialisation of the namespace and also setting permissions to read configmaps to the namespace.

Step 3 deals with installation of OPA with kube-mgmt as a sidecar

Step 4-7 deals with loading policies (and any associated data) to OPA. Note that this step could be done at different instants of time for different policies.

Is this approach ok for delineating OPA installation with policy loading ? Please let me know your feedback. Thanks .
@roee88 @ronenkat @simanadler @ritwikc @shlomitk1
