### DISCUSSION TITLE
Make endpoint configurable in FybrikModule

### DISCUSSION THREAD

**Discussion by roee88** [fybrik/fybrik#839] [Developers] [answered]
For modules that expose an API endpoint the current code requires that endpoint to be `<releaseName>.<namespace>.svc.cluster.local`. 

The restriction to always use the (helm) release name can be removed by allowing to specify in [FybrikModule..endpoint.hostname](https://fybrik.io/dev/reference/crds/#fybrikmodulespeccapabilitiesindexapiendpoint) the endpoint exposed by the module. To make this useful it must accept a template as part of the string. This requires no changes to the current API.

For example, the current behavior is probably equivalent to:
```yaml
api:
  endpoint:
    hostname: "{{ .Values.Release.Name }}.{{ .Values.Release.Namespace }}.svc.cluster.local"
    ...
```

Any opinions?

Note: this discussion is not about exposing services across clusters although it might help in some cases (depends on the implementation for multi cluster services)
