### ISSUE TITLE
Data path could not be constructed

### ISSUE THREAD

**Issue by ityuhui** [fybrik/fybrik#1087]
Hi @shlomitk1 @roee88 

After the PR https://github.com/fybrik/fybrik/pull/1067 is merged, I meet this issue

```
10:21AM ERR controllers/app/fybrikapplication_conditions.go:59 > Setting error condition: An error was received for asset fybrik-notebook-sample/paysim-csv . If the error persists, please contact an operator.Error description: Data path could not be constructed Audit=true Controller=FybrikApplication DataSetID=fybrik-notebook-sample/paysim-csv ForUser=true app.fybrik.io/app-uuid=10aa99c6-02fc-45b3-bebd-713a0dcfdeef

```

I think the root cause maybe `capability.API.DataFormat` is removed from module spec but the function `supportsSinkInterface` does not update.

```golang
// supportsSinkInterface indicates whether the sink interface requirements are met.
func supportsSinkInterface(edge *Edge, sink *Node) bool {
	capability := edge.Module.Spec.Capabilities[edge.CapabilityIndex]
	if capability.API != nil && sink.Virtual {
		apiInterface := &app.InterfaceDetails{Protocol: capability.API.Connection.Name, DataFormat: capability.API.DataFormat}
		if match(apiInterface, sink.Connection) {.  <------------------------- AT HERE---------------------------
			return true
		}
	}
	for _, inter := range capability.SupportedInterfaces {
		if inter.Sink != nil && match(inter.Sink, sink.Connection) {
			return true
		}
	}
	return false
}
```

```
(dlv) p apiInterface
*fybrik.io/fybrik/manager/apis/app/v1alpha1.InterfaceDetails {
	Protocol: "fybrik-arrow-flight",
	DataFormat: "",}
(dlv) p sink.Connection
*fybrik.io/fybrik/manager/apis/app/v1alpha1.InterfaceDetails {
	Protocol: "fybrik-arrow-flight",
	DataFormat: "arrow",}
```
`supportsSinkInterface` will return `false`, that will trigger "Data path could not be constructed"

Could you point out what wrong/missing I am ?

**Comment by ityuhui** [comment]
Here is my yaml for FybrikApplication that comes from [sample](https://fybrik.io/dev/samples/notebook/)

Maybe I need remove "dataformat: arrow" below

```
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: my-notebook
  labels:
    app: my-notebook
spec:
  selector:
    clusterName: kind-control
    workloadSelector:
      matchLabels:
        app: my-notebook
  appInfo:
    intent: fraud-detection
  data:
    - dataSetID: "fybrik-notebook-sample/paysim-csv"
      requirements:
        interface:
          protocol: fybrik-arrow-flight
          dataformat: arrow
```

**Comment by ityuhui** [comment]
Using the latest version of FybrikApplication spec, this issue is gone.

```
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: my-notebook
  labels:
    app: my-notebook
spec:
  selector:
    workloadSelector:
      matchLabels:
        app: my-notebook
  appInfo:
    intent: Fraud Detection
  data:
    - dataSetID: "fybrik-notebook-sample/paysim-csv"
      requirements:
        interface: 
          protocol: fybrik-arrow-flight

```
