### ISSUE TITLE
Wrong fybricapplication readiness 

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1171]
The quickstart [guide ](https://fybrik.io/v0.6/samples/notebook/#create-a-fybrikapplication-resource-for-the-notebook) uses the following command to check readiness of a fabricapplication:
```
while [[ $(kubectl get fybrikapplication my-notebook -o 'jsonpath={.status.ready}') != "true" ]]; do echo "waiting for FybrikApplication" && sleep 5; done
```
but it checks the readiness of K8s CR object and doesn't check the readiness of fybrikapplication `Ready` condition.
For example in a case of a fybricapplication with following status:
```
status:
  assetStates:
    fybrik-notebook-sample/paysim-csv:
      conditions:
      - status: "False"
        type: Ready
      - message: governance policies forbid access to the data
        status: "True"
        type: Deny
      - status: "False"
        type: Error
      endpoint:
        name: ""
  observedGeneration: 2
  ready: true
```
the status check command returns `true` but the application is not read. The next quickstart steps will fail.
