### ISSUE TITLE
Handle optional tags field in Fybrik Asset

### ISSUE THREAD

**Issue by rohithdv** [fybrik/fybrik#1190]
Issue: Address the scenario when no tags are specified at the asset level. Currently Tags are not an optional field in Fybrik model. 

Illustration:

Suppose the following is loaded as an Asset in Fybrik. 
```

cat << EOF | kubectl apply -f -
apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: paysim-csv
spec:
  secretRef: 
    name: paysim-csv
  details:
    dataFormat: csv
    connection:
      name: s3
      s3:
        endpoint: "http://localstack.fybrik-notebook-sample.svc.cluster.local:4566"
        bucket: "demo"
        object_key: "PS_20174392719_1491204439457_log.csv"
  metadata:
    name: Synthetic Financial Datasets For Fraud Detection
    geography: theshire 
    tags:
      finance: true
    columns:
      - name: nameOrig
      - name: oldbalanceOrg
        tags:
          PII: true
      - name: newbalanceOrig
        tags:
          PII: true
EOF
```

**Note: nameOrig does not have tag field**

Then the katalog connector is constructing the response object as this :
`constructed katalog response: datacatalog.GetAssetResponse{ResourceMetadata:datacatalog.ResourceMetadata{Name:"Synthetic Financial Datasets For Fraud Detection", Owner:"", Geography:"theshire", Tags:taxonomy.Tags{Properties:serde.Properties{Items:map[string]interface{}{"finance":true}}}, Columns:[]datacatalog.ResourceColumn{datacatalog.ResourceColumn{Name:"nameOrig", Tags:taxonomy.Tags{Properties:serde.Properties{Items:map[string]interface{}(nil)}}}, datacatalog.ResourceColumn{Name:"oldbalanceOrg", Tags:taxonomy.Tags{Properties:serde.Properties{Items:map[string]interface{}{"PII":true}}}}, datacatalog.ResourceColumn{Name:"newbalanceOrig", Tags:taxonomy.Tags{Properties:serde.Properties{Items:map[string]interface{}{"PII":true}}}}}}, Details:datacatalog.ResourceDetails{Connection:taxonomy.Connection{Name:taxonomy.ConnectionType("s3"), AdditionalProperties:serde.Properties{Items:map[string]interface{}{"s3":map[string]interface{}{"bucket":"demo", "endpoint":"http://localstack.fybrik-notebook-sample.svc.cluster.local:4566", "object_key":"PS_20174392719_1491204439457_log.csv"}}}}, DataFormat:taxonomy.DataFormat("csv")}, Credentials:"/v1/kubernetes-secrets/paysim-csv?namespace=fybrik-notebook-sample"}`

Specifically note that

`"nameOrig", Tags:taxonomy.Tags{Properties:serde.Properties{Items:map[string]interface{}(nil)}}}`

this is unmarshalled on the other side as Tags: "null" and validation is failing..because "null" is not a valid value
```

{"level":"error","Controller":"FybrikApplication","ForUser":true,"Audit":true,"app.fybrik.io/app-uuid":"d6e8830d-96e7-4cf1-bcff-707eae4eba23","DataSetID":"fybrik-notebook-sample/paysim-csv","time":"2022-01-13T16:29:12Z","caller":"/home/runner/work/fybrik/fybrik/manager/controllers/app/fybrikapplication_conditions.go:59","message":"Setting error condition: An error was received for asset fybrik-notebook-sample/paysim-csv . If the error persists, please contact an operator.Error description: DataCatalog-AssetResponse.app.fybrik.io \"fybrik-notebook-sample/paysim-csv\" is invalid: resourceMetadata.columns.0.tags: Invalid value: \"null\": Invalid type. Expected: object, given: null"}
{"level":"trace
```

the manager is getting the following asset response object:
```
Response from `DefaultApi.GetAssetInfoPost` in GetAssetInfo of datacatalog_openapi.go: {{Synthetic Financial Datasets For Fraud Detection  theshire {{map[finance:true]}} [{nameOrig {{map[]}}} {oldbalanceOrg {{map[PII:true]}}} {newbalanceOrig {{map[PII:true]}}}]} {{s3 {map[s3:map[bucket:demo endpoint:http://localstack.fybrik-notebook-sample.svc.cluster.local:4566 object_key:PS_20174392719_1491204439457_log.csv]]}} csv} /v1/kubernetes-secrets/paysim-csv?namespace=fybrik-notebook-sample}
{"level":"info","Controller":"FybrikApplication","time":"2022-01-13T16:29:12Z","caller":"/home/runner/work/fybrik/fybrik/manager/controllers/app/fybrikapplication_controller.go:429","message":"responseJSON:{\"resourceMetadata\":{\"name\":\"Synthetic Financial Datasets For Fraud Detection\",\"geography\":\"theshire\",\"tags\":{\"finance\":true},\"columns\":[{\"name\":\"nameOrig\",\"tags\":null},{\"name\":\"oldbalanceOrg\",\"tags\":{\"PII\":true}},{\"name\":\"newbalanceOrig\",\"tags\":{\"PII\":true}}]},\"details\":{\"connection\":{\"name\":\"s3\",\"s3\":{\"bucket\":\"demo\",\"endpoint\":\"http://localstack.fybrik-notebook-sample.svc.cluster.local:4566\",\"object_key\":\"PS_20174392719_1491204439457_log.csv\"}},\"dataFormat\":\"csv\"},\"credentials\":\"/v1/kubernetes-secrets/paysim-csv?namespace=fybrik-notebook-sample\"}"}
```

specifically you can note that` {\"name\":\"nameOrig\",\"tags\":null},  ..`

Expected Output: 
Katalog connector should not to send Tags value during Marshalling for `nameOrig` field as it is not specified in the fybrik `Asset`.
