### ISSUE TITLE
The manager chooses a `read` step in a `write` flow

### ISSUE THREAD

**Issue by Mohammad-nassar10** [fybrik/fybrik#1377]
In a case where there exists a `fybrikapplication` with `write` flow with `dataformat` different from the `dataformat` in the asset. The manager creates a plotter with the following flows:
`[{Name:s3/new-dataset-write FlowType:write AssetID:s3/new-dataset SubFlows:[{Name: FlowType:write Triggers:[workload] Steps:[[{Name: Cluster:thegreendragon Template:write Parameters:0xc000c06e40} {Name: Cluster:thegreendragon Template:read Parameters:0xc000c06f00}]]}]}]`. Where there are `write` and `read` steps.
The following are the full `fybrikapplication.yaml`, `fybrikmodule.yaml`, and the plotter:
```
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: write-csv-parquet
  namespace: default
  labels:
    app: notebook
spec:
  selector:
    clusterName: thegreendragon
    workloadSelector:
      matchLabels:
        app: notebook
  appInfo:
    intent: Fraud Detection
    role: Security
  data:
  - dataSetID: "s3/new-dataset"
    flow: write
    requirements:
      interface:
        protocol: s3
        dataformat: csv
```
```
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: read-write-parquet
  namespace: fybrik-system
spec:
  chart:
    name:  ghcr.io/fybrik/fybrik-template:0.1.0
  type: service
  capabilities:
    - capability: read
      scope: workload
      actions:
        - name: RedactAction
        - name: RemoveAction
      api:
        connection:
          name: fybrik-arrow-flight
          fybrik-arrow-flight:
            hostname: read-write-module
            port: 80
            scheme: grpc
      supportedInterfaces:
      - source:
          protocol: s3
          dataformat: parquet
      - source:
          protocol: s3
          dataformat: csv
    - capability: write
      scope: workload
      api:
        connection:
          name: fybrik-arrow-flight
          fybrik-arrow-flight:
            hostname: read-write-module
            port: 80
            scheme: grpc
      supportedInterfaces:
      - sink:
          protocol: s3
          dataformat: parquet
      - sink:
          protocol: s3
          dataformat: csv
```

`&{TypeMeta:{Kind:Plotter APIVersion:app.fybrik.io/v1alpha1} ObjectMeta:{Name:write-csv-parquet-default GenerateName: Namespace:fybrik-system SelfLink: UID: ResourceVersion:1 Generation:0 CreationTimestamp:0001-01-01 00:00:00 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:notebook app.fybrik.io/app-name:write-csv-parquet app.fybrik.io/app-namespace:default] Annotations:map[app.fybrik.io/app-uuid:18] OwnerReferences:[] Finalizers:[Plotter.finalizer] ClusterName: ManagedFields:[]} Spec:{Selector:{ClusterName:thegreendragon WorkloadSelector:{MatchLabels:map[app:notebook] MatchExpressions:[]}} AppInfo:{Properties:{Items:map[intent:Fraud Detection role:Security]}} Assets:map[s3/new-dataset:{AdvertisedAssetID: DataStore:{Vault:map[delete:{Role: SecretPath: Address: AuthPath:} read:{Role: SecretPath: Address: AuthPath:} write:{Role: SecretPath: Address: AuthPath:}] Connection:{Name:s3 AdditionalProperties:{Items:map[s3:map[bucket:fybrik-test-bucket endpoint:s3.eu-gb.cloud-object-storage.appdomain.cloud object_key:small.csv]]}} Format:parquet}}] Flows:[{Name:s3/new-dataset-write FlowType:write AssetID:s3/new-dataset SubFlows:[{Name: FlowType:write Triggers:[workload] Steps:[[{Name: Cluster:thegreendragon Template:write Parameters:0xc0007ee000} {Name: Cluster:thegreendragon Template:read Parameters:0xc0007ee0c0}]]}]}] ModulesNamespace:fybrik-blueprints Templates:map[read:{Name:read Modules:[{Name:read-write-parquet Type:service Chart:{Name:ghcr.io/fybrik/fybrik-template:0.1.0 ChartPullSecret: Values:map[]} Scope:workload Capability:read}]} write:{Name:write Modules:[{Name:read-write-parquet Type:service Chart:{Name:ghcr.io/fybrik/fybrik-template:0.1.0 ChartPullSecret: Values:map[]} Scope:workload Capability:write}]}]} Status:{ObservedState:{Ready:false Error:} ObservedGeneration:0 Flows:map[] Assets:map[] Blueprints:map[] Conditions:[] ReadyTimestamp:<nil>}}`
