### ISSUE TITLE
Handle writing new dataset with catalog registration

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#1458]
This issue deals with the case of writing new asset which is not register in the catalog. It means that fybrik manager should be responsible for allocating storage to hold the new data and then register it to the catalog. 
The following existing fields are set in the fybrikapplication for this case: 
```  
     requirements:
        flowParams:
          isNewDataSet: true
          catalog: catalog-id
```
