### ISSUE TITLE
Confusing message in fybrik application status

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#1493]
When deploying fybrikapplication with write flow and with a policy preventing to use existing storage account the following message appears in the fybrikapplication status: `Deployed modules do not provide the functionality required to construct a data path for new-data-parquet` while the manager log reveals the true reason for the fail: `Could not find a storage account, aborting data path construction`

```
  Asset States:
    New - Data - Parquet:
      Conditions:
        Status:   False
        Type:     Ready
        Status:   False
        Type:     Deny
        Message:  An error was received for asset new-data-parquet . If the error persists, please contact an operator.Error description: Deployed modules do not provide the functionality required to construct a data path for new-data-parquet
        Status:   True
        Type:     Error
```

the policy deployed:
```
      package dataapi.authz

     rule[{"action": {"name":"RedactAction","columns": column_names}, "policy": description}] {
        description := "Redact written columns tagged as sensitive in datasets tagged with finance = true"
        input.action.actionType == "write"
        input.action.destination != "theshire"
        column_names := [input.resource.metadata.columns[i].name | input.resource.metadata.columns[i].tags.sensitive]
      }
```

storage account: 
```
apiVersion:   app.fybrik.io/v1alpha1
kind:         FybrikStorageAccount
metadata:
  name: theshire-storage-account
  namespace: fybrik-system
spec:
  id: theshire-object-store
  region: theshire
  endpoint: "http://s3.fybrik-system.svc.cluster.local:9090"
  secretRef:  bucket-creds

```

fybrikapplication:
```
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: my-notebook-write-new
  namespace: fybrik-notebook-sample
  labels:
    app: my-notebook-write
spec:
  selector:
    clusterName: thegreendragon
    workloadSelector:
      matchLabels:
        app: my-notebook-write
  appInfo:
    intent: Fraud Detection
  data:
    - dataSetID: 'new-data-parquet'
      flow: write
      requirements:
        flowParams:
          isNewDataSet: true
          catalog: fybrik-notebook-sample
          metadata:
            tags:
              finance: true
            columns:
            - name: nameOrig
              tags:
                PII: true
            - name: oldbalanceOrg
              tags:
                sensitive: true
        interface:
          protocol: fybrik-arrow-flight

```

log message from the manager:

```
{"level":"debug","Controller":"FybrikApplication","FybrikApplication":"fybrik-notebook-sample/my-notebook-write-new","app.fybrik.io/app-uuid":"e4b4efbb-2500-4cbc-a54c-3c87865ce2e2","DataSetID":"new-data-parquet","time":"2022-05-16T03:27:46Z","caller":"/data/the-mesh-for-data/manager/controllers/app/select_modules.go:128","message":"Could not find a storage account, aborting data path construction"}
```
