### ISSUE TITLE
Check dependencies 

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1507]
Fybrik assumes the existence of Vault and datashim for some of the modules. 
Requirements and instructions for datashim deployment are not evident in the Fybrik documentation. 
Fybrik doesn't check that datashim is deployed, and if `storage_provisioning` tries run `CreateDataset` eventually the application gets the following status error:
```yaml
Status:
  Asset States:
    New - Data:
      Conditions:
        Status:   False
        Type:     Ready
        Status:   False
        Type:     Deny
        Message:  An error was received for asset new-data . If the error persists, please contact an operator.Error description: no matches for kind "Dataset" in version "com.ie.ibm.hpsys/v1alpha1"
        Status:   True
        Type:     Error
      Endpoint:
        Name:
```
The issue is related to the wider discussion about usage of datashim. But if we continue to use it, we have to update documentation and add prerequirements checks with relevant error messages. (the same for Vault)
