### ISSUE TITLE
Add chart values to HelmValues structure

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1549]

**Comment by shlomitk1** [comment]
On the second thought, chart values are unstructured data, and can not be added to the structured HelmValues. 
For example, module values: 
```
      image.tag: 0.11.0
      image.pullPolicy: Always
      labels.component: arrow-flight-module
```
will be "all over the place" in the resulted values:
```
image:
  tag: 0.11.0
  pullPolicy: Always
labels:
  app.fybrik.io/app-name: my-notebook-read
  namespace: fybrik-notebook-sample
  component: arrow-flight-module
uuid: 12345678
...
```
