### ISSUE TITLE
Fix a misleading statement in the manager-deployment.yaml` file

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1665]
The `manager-deployment.yaml` file contains the following statement 
```yaml
metadata:
      {{- with .Values.manager.podAnnotations }}
      annotations:
        sidecar.istio.io/inject: "true"
        {{- toYaml . | nindent 8 }}
      {{- end }}
``` 
It's not clear what is a relationship between  `podAnnotations` and istio sidecar injection.  Why if we want to use any pod annotations, the istio sidecar injection will be set to `true`

In addition, we have to review istio usage, but it is another task.
