### ISSUE TITLE
Provide the Secret information to data connector, when vault is turned off

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1683]
Fybrik allows running deployment with vault, when `vault.enabled` is false
```yaml
# Configure the vault instance to be used by the coordinator manager
  vault:
    # WARNING: it's an advanced feature, set it to "false" if all your modules and connectors do not require getting
    # credentials from Fybrik.
    # If it is "false", you can remove all other entries below.
    enabled: true
    # Set to the Vault address.
    address: "http://vault.{{ .Release.Namespace }}:8200"
    # Login method to Vault
    login:
      # Token authentication
      token: "root"
 ```

 However, in this scenario, the data connector might use a K8s secret to access an asset. Fybrik manager should provide the secret information (name, namespace) to the data connector.
