### ISSUE TITLE
Fybrik manager panic

### ISSUE THREAD

**Issue by roytman** [fybrik/fybrik#1718]
Fybrik version:0.6.2

```
{"level":"trace","Controller":"FybrikApplication","fybrikapplication":"default/my-notebook","app.fybrik.io/app-uuid":"f44391c0-70c6-42a2-93d7-6f184a35a08f","DataSetID":"fybrik-notebook-sample/iceberg-dataset","time":"2022-09-08T12:56:39Z","caller":"/home/runner/work/fybrik/fybrik/manager/controllers/app/plotter_generator.go:152","message":"Adding module for read"}
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 340 [running]:
fybrik.io/fybrik/manager/controllers/app.moduleAPIToService(0xc000b9bda0, {0xc00057c818, 0x0}, 0xc0005b0960, {0xc00057c720, 0x40277b5fb0}, {0xc000d15f50, 0x1})
	/home/runner/work/fybrik/fybrik/manager/controllers/app/plotter_generator.go:298 +0x7dc
fybrik.io/fybrik/manager/controllers/app.(*PlotterGenerator).AddFlowInfoForAsset(0xc000780300, {0xc000b22ab0, 0xc0002787e0, {0x1, {0xc000d15f50, 0x26}, {0xc000d15f20, 0x24}, {0x0, 0x0}, ...}, ...}, ...)
	/home/runner/work/fybrik/fybrik/manager/controllers/app/plotter_generator.go:166 +0xef2
fybrik.io/fybrik/manager/controllers/app.(*FybrikApplicationReconciler).buildSolution(0xc00055e0f0, {{{0x2509ed8, 0xc000a8d3b0}, 0xff, {0x0, 0x0}, {0xc000a2aa00, 0x8b, 0x1f4}, {0xc0009c4700, ...}, ...}, ...}, ...)
	/home/runner/work/fybrik/fybrik/manager/controllers/app/fybrikapplication_controller.go:715 +0x76f
fybrik.io/fybrik/manager/controllers/app.(*FybrikApplicationReconciler).reconcile(0xc00055e0f0, {{{0x2509ed8, 0xc000a8d3b0}, 0xff, {0x0, 0x0}, {0xc000a2aa00, 0x8b, 0x1f4}, {0xc0009c4700, ...}, ...}, ...})
	/home/runner/work/fybrik/fybrik/manager/controllers/app/fybrikapplication_controller.go:374 +0x389
fybrik.io/fybrik/manager/controllers/app.(*FybrikApplicationReconciler).Reconcile(0xc00055e0f0, {0x2523900, 0xc0008562d0}, {{{0xc000b02b09, 0x20619e0}, {0xc000b02af4, 0xc0009a2140}}})
	/home/runner/work/fybrik/fybrik/manager/controllers/app/fybrikapplication_controller.go:137 +0xc4a
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000948b40, {0x2523858, 0xc00091d340}, {0x1f88000, 0xc000a3aba0})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298 +0x303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000948b40, {0x2523858, 0xc00091d340})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:210 +0x354
```
	
module yaml
```yaml
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: trino-module
  labels:
    name: trino-module
    version: 0.0.1  # semantic version
  namespace: fybrik-system
spec:
  type: service
  chart:
    name: ghcr.io/mohammad-nassar10/trino-module-chart:0.2.0
    values:
      imageChart.tag: 0.2.0
  capabilities:
    - capability: read
      scope: workload
      api:
        connection:
          name: trino
          rest:
            endpoint: "https://{{ .Release.Name }}.{{ .Release.Namespace }}:80/readAsset"
      supportedInterfaces:
        - source:
            protocol: trino
            dataformat: iceberg
      actions:
        - name: RedactAction
        - name: RemoveAction
 ```

**Comment by roytman** [comment]
see
```yaml
connection:
          name: trino
          rest:
```
