### ISSUE TITLE
Adapt FybrikStorageAccount to other connection types 

### ISSUE THREAD

**Issue by shlomitk1** [fybrik/fybrik#1744]
Add `type` and `geography`.
Add connection properties according to the connection taxonomy.
Example:
```
spec:
  id: theshire-object-store
  type: s3
  secretRef: credentials-theshire
  geography: theshire
  s3:
    region: eu
    endpoint: http://s3.eu.cloud-object-storage.appdomain.cloud
 ```
