### ISSUE TITLE
Consider deploying OPA chart from opa repo

### ISSUE THREAD

**Issue by revit13** [fybrik/fybrik#2023]
taken from https://github.com/open-policy-agent/kube-mgmt/tree/master/charts/opa-kube-mgmt

```
helm repo add opa https://open-policy-agent.github.io/kube-mgmt/charts
helm repo update
helm upgrade -i -n opa --create-namespace opa opa/opa-kube-mgmt

**Comment by shlomitk1** [comment]
Where will opa be deployed? In "opa" ns or in "fybrik-system" ns?

**Comment by roytman** [comment]
@revit13 usage of this chart requires some integration work, e.g. we have to connect .`Values.admissionController.enabled` with our cluster scope, and others.

@shlomitk1 , we can install it in the "fybrik-system" by running:
`helm upgrade -i -n  fybrik-system  opa/opa-kube-mgmt`

**Comment by tomersolomon1** [comment]
I looked at this last weeks and my findings are as follows. Generally speaking, this can be done.

Here are some options:
1. Deploy OPA as we currently deploy Vault, i.e. as a "third party". The main downside seems to be that we need to update our documentation + tests.
2. Deploy OPA as a dependency to our helm chart, for example in the following way (in `Chart.yaml`):
```yaml
dependencies:
  - name: opa-kube-mgmt
    version: "8.1.0"
    repository: "https://open-policy-agent.github.io/kube-mgmt/charts"
```
We can dictate OPA's values using our main `values.yaml` with:
```yaml
...
# push values down to opa-kube-mgmt
opa-kube-mgmt:
  annotations:
    foo: "bar"
```
However, note that helm *doesn't automatically* fetch such dependencies. Instead one should first run `[helm dependencies update](https://kb.novaordis.com/index.php/Helm_dependency#Dependency_Update)`, to download the chart to be under the `charts` subdirectory. See [this](https://kb.novaordis.com/index.php/Helm_Dependencies) for details. I suppose we can do that ourselves when we publish our chart.
