### ISSUE TITLE
Unable to use fybrikmodules that reference charts in authenticated repos

### ISSUE THREAD

**Issue by ngoracke** [fybrik/fybrik#716]
The end to end m4dapplication test references a module defined as such:

```
apiVersion: app.m4d.ibm.com/v1alpha1
kind: M4DModule
metadata:
  name: read-module-test-e2e
  namespace: m4d-system
spec:
  chart:
    name: localhost:5000/m4d-system/m4d-template:0.1.0
  flows:
    - read
```

In the case where the chart is stored in an authenticated registry (artifactory, quay, etc), how would one make that work?  I didn't see anything in the module spec to handle authentication, but perhaps I didn't look hard enough.
