### ISSUE TITLE
Specify user required data flow type in fybrikapplication

### ISSUE THREAD

**Issue by froesef** [fybrik/fybrik#927]
A user should be able to specify the data flow type(s) that should be provided for the application. Currently the default assumption is always to read. But writing should also be an option as well as possibly specifying a copy that way.

The proposal is to add a new field that contains all data flows that the user is requesting.
```
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: my-notebook
  namespace: fybrik-notebook-sample
  labels:
    app: my-notebook
spec:
  selector:
    clusterName: thegreendragon
    workloadSelector:
      matchLabels:
        app: my-notebook
  appInfo:
    intent: fraud-detection
  data:
    - dataSetID: 'fybrik-notebook-sample/data-csv'
      requirements:
        dataFlows: ["write"]                  <-- new field
        interface:
          protocol: fybrik-arrow-flight
          dataformat: arrow


```

**Comment by shlomitk1** [comment]
This will make `copy -> required: bool ` not needed. As for `copy -> catalog: {}` that indicates how to register a new asset, I suggest to move `catalog` directly under requirements. 
For example:
```
data:
    - dataSetID: 'fybrik-notebook-sample/data-csv'
      requirements:
        dataFlows: 
        - copy
        interface:
          protocol: fybrik-arrow-flight
          dataformat: arrow
        catalog:
           id: myNewCatalog
           service: WKC
```
